### ISSUE TITLE
BFS 4th Script Error

### ISSUE THREAD

**Issue by TomLight343** [KastnerRG/spector#1]
No such file or directory "bfs_params.log".
Since this was right after the third script ran the synthesis on the designs, shouldn't the fourth script read from the estimateResults.log file?

**Comment by qkgautier** [comment]
It seems that I updated the first script, which changed the name from "bfs_params.log" to "params.log" and I didn't update the 4th script to reflect this change. Thanks for catching that!
I will update this shortly.
Also, it's better that this script reads from "params.log" because it contains the knob parameters as well.
